/* ============================================================
   UnspokenArchive — Data Layer
   50 stories · 35 tips · 52 terminology entries
   localStorage keys: ua_stories · ua_tips · ua_terms
   ============================================================ */

const HERO_PHRASES = [
  "Tell me.",
  "I want to listen.",
  "Help someone understand.",
  "You are not the only one.",
  "To be loved is to be changed.",
  "Healing is not linear.",
  "Someone survived what you are surviving.",
  "The quiet stories matter too.",
  "You made it through something.",
  "Someone understands.",
  "You do not have to explain yourself to exist.",
  "The hardest things are the truest things."
];

const QUOTES = [
  "Healing is not linear.",
  "Surviving is not small.",
  "Someone understands.",
  "You made it through something.",
  "Vulnerability is the birthplace of connection.",
  "The quiet stories matter too.",
  "We are all broken — that's how the light gets in.",
  "You are not your worst moment.",
  "Recovery is not a destination. It is a direction.",
  "Your story is not over.",
  "Rest is not the enemy of progress.",
  "You were never too much. You were always just enough.",
  "The truth of what happened to you belongs to you.",
  "Some things cannot be fixed. They can only be carried differently over time."
];

const CATEGORIES = [
  "Depression", "Anxiety", "Trauma", "Grief", "Addiction",
  "Eating Disorders", "Loneliness", "Bullying", "Family Conflict",
  "Identity", "Recovery", "Survival", "Childhood Experiences",
  "Relationships", "Burnout", "Isolation", "Body Image", "Loss"
];

const ADVICE_CATEGORIES = [
  "Anxiety", "Depression", "Grief", "Addiction Recovery",
  "Eating Disorders", "PTSD", "Loneliness", "Insomnia",
  "Burnout", "Social Anxiety", "Panic Attacks",
  "Relationship Trauma", "Childhood Trauma", "Self-Harm Recovery"
];

/* ============================================================
   STORIES — 50 entries across all 18 categories
   Raw, first-person, 150-320 words, emotionally authentic.
   Eating disorder content: no numbers (no cal/weight/size).
   ============================================================ */
const DEFAULT_STORIES = [

  /* Depression */
  { id:"s1", title:"3am Again", content:"I have become an expert at pretending. Eight hours of convincing people I'm fine. Laughing at the right moments. Asking follow-up questions so they think I'm engaged. At 3am the mask comes off and I just stare at the ceiling and wonder how something invisible can be so heavy. Depression doesn't look the way they show it in movies. It doesn't look like staying in bed all day — at least not for me. It looks like me at my desk, answering emails, making plans I'll cancel, laughing at someone's joke, dying a little inside. The most exhausting part isn't the sadness. It's the performing that goes around it.", category:"Depression", readingTime:2, createdAt:"2026-02-01T03:00:00Z", reactions:{heart:287,hug:198,meToo:231,strength:94}, triggerWarnings:[] },
  { id:"s2", title:"The Good Days Are the Hardest", content:"People don't tell you that the good days can be the cruelest thing about depression. You have three good days and you think: maybe it's over, maybe I'm through it. Then it comes back and you fall twice as far because you had started to believe in solid ground again. I've learned to treat the good days carefully now. Not to spend them all, not to promise people things I might not be able to deliver on Thursday. It's a kind of grief, honestly — grieving the person who used to make plans without calculating the odds of being able to keep them. I'm still making plans. I'm just honest about what they are.", category:"Depression", readingTime:2, createdAt:"2026-02-08T14:00:00Z", reactions:{heart:341,hug:212,meToo:298,strength:87}, triggerWarnings:[] },
  { id:"s3", title:"Anhedonia", content:"The worst symptom nobody talks about is when things that used to make you feel good just don't. Not sadness. Not even numbness exactly. More like trying to remember what a song sounded like from inside a soundproofed room. I used to love cooking. I used to spend entire Saturdays in the kitchen, inventing things. For a year and a half I survived on food that required the least possible engagement. I bought the same things on repeat and didn't taste them. When I finally cooked something from scratch again — a simple pasta — I cried for twenty minutes afterwards. Not because it was bad. Because it tasted like something. Like me.", category:"Depression", readingTime:2, createdAt:"2026-02-15T18:00:00Z", reactions:{heart:401,hug:267,meToo:189,strength:145}, triggerWarnings:[] },
  { id:"s4", title:"The Pill That Helped", content:"I resisted medication for three years. I had a story about what it meant — about strength, about authenticity. Those stories were wrong. The medication didn't change who I am. It changed whether I could access who I am. There's a version of me underneath the depression that existed before it and exists when I'm well. The medication doesn't create that version. It just lets me reach it. I'm telling this because I wasted three years of recoverable time on pride. If you're in the same place: the story you're telling yourself about what it means isn't necessarily true.", category:"Depression", readingTime:2, createdAt:"2026-03-09T14:00:00Z", reactions:{heart:612,hug:389,meToo:312,strength:534}, triggerWarnings:[] },

  /* Anxiety */
  { id:"s5", title:"The Mall", content:"Last Tuesday I had to leave a shopping mall because I couldn't breathe. Not because anything happened. Because everything happened — too many people moving too fast, too much noise layered on noise. My chest closed up before I had time to notice it happening. I sat in my car for forty minutes before I could drive. I called in sick the next day and spent the whole morning convincing myself I wasn't broken. The word 'broken' means something damaged beyond use. I am not damaged beyond use. I am learning which environments I can be in and which ones cost more than I have that day. That's not broken. That's information.", category:"Anxiety", readingTime:2, createdAt:"2026-02-04T11:00:00Z", reactions:{heart:189,hug:142,meToo:267,strength:78}, triggerWarnings:["Panic attack"] },
  { id:"s6", title:"The What-If Machine", content:"My brain is a what-if machine that runs at full speed at all times. What if I said the wrong thing yesterday. What if they didn't mean it like that. What if I'm always going to be this way. My therapist asked me once: what is the what-if machine trying to protect you from? I sat with that for a long time. I think it's trying to protect me from being surprised. From being caught off guard. Like if I've already worried about everything, nothing can hurt me unexpectedly. It doesn't work. But I understand why it keeps trying.", category:"Anxiety", readingTime:2, createdAt:"2026-02-19T22:00:00Z", reactions:{heart:356,hug:201,meToo:421,strength:112}, triggerWarnings:[] },
  { id:"s7", title:"The Email", content:"I drafted an email for eleven days before sending it. One email. To a colleague I've worked with for four years. It was a professional email about a project handover. I wrote it, deleted it, wrote it again, left it in drafts for three days, read it back, changed three words, left it another two days. In the end I sent it at 11pm on a Tuesday because that felt like the safest time. She replied in eight minutes with 'Perfect, thanks.' Eleven days. Eight minutes. I'm learning to set a timer now. I allow myself to edit twice. Then I send it. The world has not ended yet.", category:"Anxiety", readingTime:2, createdAt:"2026-03-02T16:00:00Z", reactions:{heart:512,hug:234,meToo:489,strength:167}, triggerWarnings:[] },
  { id:"s8", title:"Before Every Room", content:"Before I enter any room with more than three people, I stand outside the door for a moment. Running the simulation — who's in there, what will be expected, how loud will it be. People think I'm confident. I'm not. I'm extremely well-rehearsed. There's a difference. The rehearsal is exhausting. I cancel things more than I should. I cancel and then feel relief followed immediately by shame. My therapist says the avoidance is feeding the fear. I know. I know. I'm working on smaller rooms first.", category:"Anxiety", readingTime:2, createdAt:"2026-03-23T17:00:00Z", reactions:{heart:567,hug:389,meToo:634,strength:145}, triggerWarnings:[] },
  { id:"s9", title:"The Thing I Can't Say Out Loud", content:"I've had intrusive thoughts since I was a teenager and I've never told anyone because they are the kind that, if I described them, would make people afraid of me. They make me afraid of me. The difference — the thing I finally learned — is that having a thought is not the same as wanting to act on it. My brain generates these images the way a malfunctioning printer generates noise. The content does not represent me. The distress actually proves the opposite: I'm horrified by them because they contradict everything I am. That knowledge took years to arrive. I hope it arrives faster for whoever needs to read this.", category:"Anxiety", readingTime:2, createdAt:"2026-03-26T08:00:00Z", reactions:{heart:789,hug:567,meToo:398,strength:312}, triggerWarnings:["Intrusive thoughts"] },

  /* Trauma */
  { id:"s10", title:"The Weight of Silence", content:"I have carried this secret for twenty years. It sits in my chest like a cold stone. Every time I try to speak it, the words catch in my throat, as if my body itself is protecting the lie. Therapists asked the right questions. I gave the wrong answers. Not because I wanted to deceive them — because I had spent so long protecting other people from what I knew that I had almost started protecting myself from it too. But today, writing it here, I feel the stone begin to crack. Maybe that is enough. Maybe beginning is the whole thing.", category:"Trauma", readingTime:2, createdAt:"2026-02-10T10:00:00Z", reactions:{heart:498,hug:334,meToo:201,strength:387}, triggerWarnings:["Long-held trauma"] },
  { id:"s11", title:"Body Memory", content:"Nobody told me that trauma lives in the body. That my shoulders would tense in certain rooms before my brain had registered why. That a particular cologne on a stranger would make my hands start shaking. I spent years thinking I was overreacting, inventing connections. Then a physiotherapist — of all people — said: your body remembered something your mind was still protecting you from. It took another year in therapy to understand what she meant. I still have the shoulder tension. But now I know it's telling me something. I've learned to listen to it rather than override it.", category:"Trauma", readingTime:2, createdAt:"2026-02-22T09:00:00Z", reactions:{heart:421,hug:298,meToo:312,strength:267}, triggerWarnings:[] },
  { id:"s12", title:"The Smell of Rain on Hot Tarmac", content:"The smell of rain on hot tarmac takes me there immediately. Not gradually — immediately. Before I have a chance to do any grounding, before I can name what's happening, I'm back in that car park, it's that evening, and my body doesn't know yet that it's over. EMDR has helped. I'm not going to oversell it or pretend I'm fixed. But the return journeys are shorter now. I come back faster. And when I do, I know where I am. That used to take much longer. Progress in PTSD looks like shorter trips back. That's what nobody tells you.", category:"Trauma", readingTime:2, createdAt:"2026-02-13T11:00:00Z", reactions:{heart:445,hug:312,meToo:389,strength:267}, triggerWarnings:["Trauma response", "Flashback"] },

  /* Grief */
  { id:"s13", title:"The Empty Chair", content:"Grief is just love with nowhere to go. I still set the table for two sometimes, out of habit or hope — I don't know which anymore. The silence in the kitchen is the loudest thing I've ever heard. They told me about the five stages. I went through them all in the wrong order, more than once. I don't think grief has stages. I think grief has weather. Some days it's a grey drizzle you can function through. Some days it's a storm you just have to wait out inside. I'm learning to stop apologizing for which kind of day it is.", category:"Grief", readingTime:2, createdAt:"2026-02-18T09:15:00Z", reactions:{heart:587,hug:421,meToo:234,strength:312}, triggerWarnings:["Bereavement"] },
  { id:"s14", title:"Her Red Coat", content:"My daughter died on a Tuesday. She was four. She had a red coat she refused to take off even in summer because she said it was her favourite colour in the whole world. In the two years since, I have learned that grief does not follow any of the rules anyone told me about. The coat is still in the closet. I can't move it but I can't throw it away. I see little girls in red coats at the park and I have to leave. I don't think that will stop. I don't think I want it to. It means she was here. She was so entirely, loudly, beautifully here.", category:"Grief", readingTime:2, createdAt:"2026-03-13T10:00:00Z", reactions:{heart:892,hug:734,meToo:98,strength:567}, triggerWarnings:["Child loss", "Bereavement"] },
  { id:"s15", title:"Performing Okay", content:"My mother died in October. By November I was back at work. Not because I was ready. Because I didn't know what I would be if I stopped moving. Grief had no tasks. Just time and the absence where she used to be. I held it together so well that people stopped asking. That was the loneliest part — performing okay so convincingly that there was nowhere left to fall apart. I eventually told one person at work. She cried. I felt less alone. That's all I needed. One person who stopped believing the performance.", category:"Grief", readingTime:2, createdAt:"2026-03-20T11:00:00Z", reactions:{heart:445,hug:312,meToo:267,strength:198}, triggerWarnings:["Parental loss"] },

  /* Addiction */
  { id:"s16", title:"The Bottle", content:"I hid bottles in seven different places in my apartment. I knew exactly where each one was the way you know where your keys are — without thinking, just knowing. I thought no one knew. My sister knew. My manager knew. My downstairs neighbour knew. I was the last one to know. Sobriety is the strangest thing. It feels like learning to stand up after years of leaning. Everything I drank to not feel, I feel now. It all arrived eventually. But I feel other things too, now. Things I forgot were mine.", category:"Addiction", readingTime:2, createdAt:"2026-03-15T19:00:00Z", reactions:{heart:445,hug:312,meToo:234,strength:389}, triggerWarnings:["Alcohol addiction"] },
  { id:"s17", title:"Finding the Light", content:"Recovery isn't a straight line. It's a messy, circular path that often leads you back to where you started, but with a slightly better map. I used to think being clean was the goal. Then I got there and realised I had no idea who I was without the substance. The real work started after. Some days I still lose. I reach for old habits the way you reach for a light switch in a room you've lived in for years — out of muscle memory, not intention. But I'm still here. And that has to count for something.", category:"Addiction", readingTime:2, createdAt:"2026-02-14T14:30:00Z", reactions:{heart:356,hug:245,meToo:178,strength:421}, triggerWarnings:[] },
  { id:"s18", title:"What Relapse Taught Me", content:"My relapse happened on a Sunday, in a car park, in the rain. I had been sober for eight months. I thought a relapse would feel like failure. It felt like shame so thick I couldn't see through it. What it actually was — and I could only see this later — was data. It told me exactly what I hadn't dealt with, which triggers I'd been outrunning. A relapse is not the end of the story. I know that now. I tell this to myself on the bad days. The story kept going. It is still going.", category:"Addiction", readingTime:2, createdAt:"2026-03-08T20:00:00Z", reactions:{heart:523,hug:389,meToo:267,strength:445}, triggerWarnings:[] },

  /* Eating Disorders */
  { id:"s19", title:"Mirror Season", content:"For years I counted everything. I thought control was the point. What I actually controlled was nothing. The numbers were a language for something I didn't have words for yet — that I didn't feel safe inside my own body, that I didn't believe I deserved to take up space. Recovery from that is quieter than I expected. Nobody gives you a chip. There are just mornings where you eat breakfast and don't immediately calculate what it cost you. I'm working on it. Some days it's just breakfast. Those days feel like victories I am very careful not to announce too loudly, in case they leave.", category:"Eating Disorders", readingTime:2, createdAt:"2026-03-17T07:00:00Z", reactions:{heart:523,hug:412,meToo:345,strength:278}, triggerWarnings:["Disordered eating", "Body image"] },
  { id:"s20", title:"The Compliments", content:"People kept telling me I looked amazing. That was the most dangerous part. The illness convinced me that the comments proved something — that I was finally enough. It took a long time to understand that the compliments were one of the things making me sicker. Not because the people saying them were cruel — they weren't. They were using the only language they had, which is our culture's language about bodies, which is broken. I am careful now about what I say to people about their bodies. I say nothing at all, usually. Their bodies are their business. I learned that one the hard way.", category:"Eating Disorders", readingTime:2, createdAt:"2026-03-24T15:00:00Z", reactions:{heart:612,hug:445,meToo:398,strength:201}, triggerWarnings:["Disordered eating"] },

  /* Loneliness */
  { id:"s21", title:"Sunday Silence", content:"I have hundreds of contacts in my phone. On Sunday I sat in my apartment for eleven hours without speaking to a single one of them. Not because no one was available. Because I couldn't explain what I needed, and I was too tired to perform being fine. Loneliness isn't about being alone. I know that now. It's about being in a room full of people and feeling utterly invisible. It's about saying something true and watching people's eyes glaze over because true things are inconvenient. I think the loneliest I've ever been was at a party with forty people who all seemed very pleased to be there.", category:"Loneliness", readingTime:2, createdAt:"2026-03-05T17:00:00Z", reactions:{heart:601,hug:445,meToo:512,strength:134}, triggerWarnings:[] },
  { id:"s22", title:"The City That Doesn't Know My Name", content:"I moved to the city for the job. Two years ago. I have colleagues. I have a gym I go to. I have a corner shop where the owner nods at me. What I do not have is a single person who would notice, in twenty-four hours, that I hadn't shown up. I've started going to a book group. I don't love all the books. But I love that for two hours on a Thursday, six people know my first name and expect to see me. That's a beginning. I'm treating it like one.", category:"Loneliness", readingTime:2, createdAt:"2026-02-28T20:00:00Z", reactions:{heart:489,hug:312,meToo:423,strength:156}, triggerWarnings:[] },

  /* Bullying */
  { id:"s23", title:"What They Called Me", content:"They called me a name every day for three years. Different kids, same name. I've been out of school for a decade and I still hear it sometimes when someone raises their voice near me. Not literally. But in the gut — the old contraction, the waiting. I never told a teacher. I told my parents once, who told me to ignore it. Ignoring it was not advice. It was abandonment dressed up as advice. I've done a lot of work on this. I understand now that what they did says everything about what they'd been taught and nothing about who I am. I just wish someone had told me that at the time.", category:"Bullying", readingTime:2, createdAt:"2026-02-12T15:00:00Z", reactions:{heart:445,hug:312,meToo:389,strength:267}, triggerWarnings:[] },
  { id:"s24", title:"The Group Chat", content:"I was removed from a group chat by people I had known for six years. No explanation. No conversation. I'm forty-three years old. I felt like I was fifteen again. I spent two weeks cycling through every conversation we'd ever had, trying to find the thing I'd done. I never found it. Adult bullying doesn't look like the movies. It looks like silence. It looks like exclusion so quiet and clean that you can't even name it to anyone without sounding paranoid. But I know what happened. And I know it wasn't nothing.", category:"Bullying", readingTime:2, createdAt:"2026-03-18T12:00:00Z", reactions:{heart:356,hug:245,meToo:412,strength:123}, triggerWarnings:[] },

  /* Family Conflict */
  { id:"s25", title:"Dinner Table", content:"My mother hasn't spoken to me in eleven months because I told her something true about our family. Not something unkind. Something true. There is a version of this where she comes back around. There is a version where she doesn't. I am trying to be okay with not knowing which version I'm in. I am building something smaller and quieter now, with people who stay when things are true, who don't need me to edit the past to make them comfortable. It is a smaller table. But everyone at it is actually there.", category:"Family Conflict", readingTime:2, createdAt:"2026-03-16T18:00:00Z", reactions:{heart:512,hug:378,meToo:412,strength:245}, triggerWarnings:[] },
  { id:"s26", title:"The Family Everyone Envied", content:"From outside, we looked like the kind of family people talked about approvingly. Nice house. Good manners. Everyone did well. Inside, no one touched anything real. I grew up unable to ask for things directly because nothing important was ever said directly. I'm still unlearning this. My partner says I speak in code sometimes. I'm working on the translation.", category:"Family Conflict", readingTime:2, createdAt:"2026-03-22T09:00:00Z", reactions:{heart:389,hug:267,meToo:334,strength:156}, triggerWarnings:[] },

  /* Identity */
  { id:"s27", title:"In Between", content:"Coming out to myself took longer than coming out to anyone else. There were years of being half a person, of performing a version of myself that felt like wearing clothes several sizes wrong. I still don't have all the words for who I am. I don't think I need all of them yet. I'm learning that the not-knowing can be the space where you actually live, rather than the problem to solve before you start living. I said something true about myself to a stranger once, at 2am in an airport, and we never saw each other again. It was the most honest I'd been in years. That was the beginning.", category:"Identity", readingTime:2, createdAt:"2026-03-12T15:00:00Z", reactions:{heart:612,hug:378,meToo:489,strength:289}, triggerWarnings:[] },
  { id:"s28", title:"Between Cultures", content:"At home I was too westernised. At school I was too foreign. I learned very young that there was no version of me that both rooms could hold. I became a translator — of myself, primarily. The problem with translation is that the original gets worn down. I'm thirty-one years old and I'm still working out what I actually think versus what I learned to perform in each room. But there's a version of me underneath all of it that doesn't belong to any of those rooms and is just mine. I'm starting to furnish that room.", category:"Identity", readingTime:2, createdAt:"2026-03-25T10:00:00Z", reactions:{heart:445,hug:267,meToo:389,strength:178}, triggerWarnings:[] },

  /* Recovery */
  { id:"s29", title:"The First Saturday", content:"The first Saturday of recovery that felt like a real Saturday — not an absence, not a gap — was eleven months in. I went to the farmers market. I bought things I didn't need. I walked home slowly. I ate lunch outside. Nothing happened, which was the point. For years, every day had been organised around one central need. Having a day with no architecture except my own preferences — that was new. I cried on the walk home. A woman selling honey witnessed it. She handed me an extra paper bag. Some kindnesses are very small and exactly the right size.", category:"Recovery", readingTime:2, createdAt:"2026-02-20T14:00:00Z", reactions:{heart:512,hug:378,meToo:156,strength:489}, triggerWarnings:[] },
  { id:"s30", title:"What Recovery Looks Like from the Inside", content:"Recovery from the inside looks nothing like recovery from the outside. From the outside it looks like: functioning, maintaining, progressing. From the inside it looks like: did I manage to say something true today. Did I sit with a feeling long enough to understand what it was actually about. Did I ask for something I needed without twenty minutes of preamble justifying why I was allowed to need it. Progress in recovery is almost invisible. But I know where I started and I know where I am now. Those are different places. That is the whole point.", category:"Recovery", readingTime:2, createdAt:"2026-03-01T16:00:00Z", reactions:{heart:389,hug:256,meToo:201,strength:512}, triggerWarnings:[] },

  /* Survival */
  { id:"s31", title:"Still Here", content:"Three years ago I made a plan. I know exactly what I intended to do and when. I'm still here because my neighbour knocked on my door that afternoon to return a book she had borrowed eight months earlier. Something so small. She didn't know. She still doesn't know. I'm in a very different place now. I have a therapist I trust and a small number of people who know the real shape of things. But I think about the people who didn't get a knock on the door. I think about them all the time. That's part of why I wrote this.", category:"Survival", readingTime:2, createdAt:"2026-03-14T14:00:00Z", reactions:{heart:1204,hug:978,meToo:201,strength:934}, triggerWarnings:["Suicidal ideation — recovered"] },
  { id:"s32", title:"What I Know Now", content:"I know now that the thing I felt at my lowest was not the truth about what my life would always be. I know that because I felt it with complete certainty and it was wrong. Not slightly wrong. Completely, provably, retrospectively wrong. I'm not going to tell you what happened or how I got through it. I'm just going to say: I was sure it would never be different, and now it is different. I hope it's worth something to you reading this. People do arrive on the other side. I'm one of them.", category:"Survival", readingTime:2, createdAt:"2026-03-19T21:00:00Z", reactions:{heart:889,hug:712,meToo:156,strength:802}, triggerWarnings:[] },

  /* Childhood Experiences */
  { id:"s33", title:"What He Did", content:"I was eight years old. I told someone and no one believed me. I spent the next thirty years wondering if I remembered it wrong. Going over and over the details the way you check a locked door — not because you think it's open, but because you can't stop yourself from checking. I don't remember it wrong. I know that now. I have a therapist who helped me understand that. The work isn't done. But I know it happened, and I know it wasn't because of anything I did, and I know I am allowed to say so.", category:"Childhood Experiences", readingTime:2, createdAt:"2026-03-11T08:00:00Z", reactions:{heart:712,hug:589,meToo:267,strength:634}, triggerWarnings:["Child abuse", "Disclosure not believed"] },
  { id:"s34", title:"The House I Grew Up In", content:"The house I grew up in was not safe. Not in a dramatic way — nothing that would have made the news. In the way where you learned very young to be very quiet and to read the room before you entered any room and to make yourself small enough to not be the reason the mood changed. I'm very good at reading rooms. I'm very good at being small. These are not compliments. They are things I'm slowly trying to unlearn. My therapist calls them adaptations. Things that kept me safe then and cost me now.", category:"Childhood Experiences", readingTime:2, createdAt:"2026-02-25T12:00:00Z", reactions:{heart:634,hug:489,meToo:378,strength:312}, triggerWarnings:[] },
  { id:"s35", title:"Breaking the Chain", content:"I had a hard childhood. I will not use more detail than that because some things are mine to keep. What I will say is that when my son was born, I made a decision that was also a commitment: whatever I grew up in, stops here. Not perfectly. I make mistakes. I lose my temper. But I repair. That's the thing I didn't have — repair. When the adults in my childhood got it wrong, they didn't acknowledge it. I acknowledge it. Every time. My son knows that mistakes can be said sorry for. That is not a small thing to teach.", category:"Childhood Experiences", readingTime:2, createdAt:"2026-02-05T09:00:00Z", reactions:{heart:712,hug:489,meToo:234,strength:634}, triggerWarnings:[] },

  /* Relationships */
  { id:"s36", title:"Glass", content:"I spent three years walking on eggshells around someone I loved. Not because they hit me. They never hit me. But the silence after I said the wrong thing lasted days. The small corrections — my tone, my word choices, my opinions offered in the wrong rooms. By the end I'd forgotten who I was before I learned to be so careful. I found old journals from before. The person writing in them was louder than I am now. She had opinions she shared without checking the room first. I miss her. I'm trying to find my way back to her.", category:"Relationships", readingTime:2, createdAt:"2026-03-10T20:00:00Z", reactions:{heart:634,hug:489,meToo:312,strength:356}, triggerWarnings:["Emotional abuse"] },
  { id:"s37", title:"After the Divorce", content:"I wasn't sad my marriage ended. I was sad about who I'd been inside it. About the version of myself I'd shrunk into over twelve years. Not because of anything dramatic. Because of small accommodations made over time that I'd stopped noticing. The loneliness of divorce is strange — you're lonely for the structure, the known shape of a day, rather than for the person. I live alone now for the first time in my adult life. I cook what I want. I leave books on the floor. I'm learning that being alone is not the same as being lonely. That one took a long time.", category:"Relationships", readingTime:2, createdAt:"2026-03-06T18:00:00Z", reactions:{heart:445,hug:312,meToo:345,strength:267}, triggerWarnings:[] },
  { id:"s38", title:"Anxious Attachment", content:"I didn't have a name for it until I was thirty-four. I just thought I loved too much, needed too much, was too much. The name helped — not because a name fixes anything but because it showed me there was a mechanism, a history, a reason. I wasn't broken. I was patterned. That's a different thing. The patterns came from somewhere real, from something I learned early, from environments where love was unreliable. I'm learning the difference between a partner being unavailable and a partner being gone. It is the hardest thing I have ever done and also, slowly, working.", category:"Relationships", readingTime:2, createdAt:"2026-02-23T17:00:00Z", reactions:{heart:623,hug:412,meToo:534,strength:289}, triggerWarnings:[] },

  /* Burnout */
  { id:"s39", title:"The Last Promotion", content:"I got the promotion I had worked six years for. I sat in my car in the company parking lot that evening and cried for twenty minutes. Not from happiness. I was completely empty. Like I had spent everything I had to get there and there was nothing left inside me to enjoy it with. I quit four months later. I'm still not sure what I'm rebuilding toward. But at least I can feel things again. That has to come first.", category:"Burnout", readingTime:2, createdAt:"2026-03-08T12:00:00Z", reactions:{heart:312,hug:198,meToo:445,strength:367}, triggerWarnings:[] },
  { id:"s40", title:"Helping Is Not the Same as Healing", content:"I spent twelve years in healthcare. I went in because I wanted to help people. I left because I had nothing left. The irony of burnout in caring professions is that the same qualities that make you good at the work — empathy, investment, the inability to switch off — are the same qualities it feeds on. I thought I was being strong. I was being consumed. I'm not in that job anymore. I'm sleeping again, which I hadn't done properly in four years. I'm starting there.", category:"Burnout", readingTime:2, createdAt:"2026-02-16T08:00:00Z", reactions:{heart:489,hug:356,meToo:312,strength:423}, triggerWarnings:[] },
  { id:"s41", title:"After the PhD", content:"I finished my doctorate and immediately felt nothing. Six years. I finished on a Thursday, submitted the corrections, and sat in the library waiting to feel something. Nothing came. The thing about academic burnout is that it takes the thing you loved — the curiosity, the making of meaning — and turns it into an output machine. At the end I was writing to complete, not to understand. I'm taking a year before I decide what comes next. This is the first time in my adult life I've been allowed to not know. It's terrifying. It might also be the most honest thing I've ever done.", category:"Burnout", readingTime:2, createdAt:"2026-03-24T09:00:00Z", reactions:{heart:389,hug:245,meToo:356,strength:312}, triggerWarnings:[] },

  /* Isolation */
  { id:"s42", title:"The Lockdown That Didn't End", content:"Everyone else seemed to readjust. The world opened up and people went back to restaurants and offices and each other. I didn't. I told myself it was caution. Then preference. Then I ran out of reasons and had to admit I was afraid. Afraid of volume, of crowds, of small talk, of being seen to not know how to do this anymore. I've made myself go to two things I didn't want to go to, in the last month. They were both fine. Being fine is a start.", category:"Isolation", readingTime:2, createdAt:"2026-02-26T14:00:00Z", reactions:{heart:523,hug:389,meToo:467,strength:145}, triggerWarnings:[] },
  { id:"s43", title:"Working From Home", content:"I haven't had a spontaneous conversation with another person in six weeks. Everything is scheduled, digital, purposeful. Nobody passes my desk. Nobody makes tea and asks how I'm doing. I used to resent open-plan offices. I resent this more. The absence of the small, unremarkable contact — the nod, the shared eye-roll at the fire alarm drill — adds up. Those things were holding something together I didn't notice until they were gone. I've started taking a walk at lunchtime just to be in a space with other people. I don't talk to them. I just want to be in the same air.", category:"Isolation", readingTime:2, createdAt:"2026-03-04T15:00:00Z", reactions:{heart:423,hug:289,meToo:398,strength:112}, triggerWarnings:[] },
  { id:"s44", title:"The World Moved On", content:"I got ill at twenty-nine and stayed ill. Not dramatically. Not in a visible way. Enough to miss things. Enough to decline things. Enough to watch my social world slowly contract as people stopped asking because they expected the no. What I didn't expect was the identity loss — the slow erosion of who I was in people's eyes from a person who did things to a person who is unwell. I am still a person who does things. I do different things now, more slowly, with more planning. But I am still there inside the illness. I wish people could see that more clearly.", category:"Isolation", readingTime:2, createdAt:"2026-03-11T16:00:00Z", reactions:{heart:567,hug:423,meToo:489,strength:234}, triggerWarnings:["Chronic illness"] },

  /* Body Image */
  { id:"s45", title:"The Photo", content:"Someone tagged a photo of me from a birthday party. A genuinely happy day. I was laughing in the photo. I spent the next two hours trying to find angles that felt acceptable and then sitting on the floor feeling ashamed of having done that. The worst part wasn't the photo. The worst part was how immediately I abandoned the happy memory in favour of critiquing the evidence of it. I look back now and I see someone laughing. I want to get back to being the person who can see that without the commentary.", category:"Body Image", readingTime:2, createdAt:"2026-03-21T19:00:00Z", reactions:{heart:534,hug:389,meToo:612,strength:145}, triggerWarnings:[] },
  { id:"s46", title:"What My Body Has Done", content:"I spent so long at war with my body that it took a long time to remember what it's actually for. It has carried me through illness. It has held people I love. It has swum in cold water and danced badly at weddings and climbed things and healed from things. I'm trying to remember it as the vehicle, not the verdict. Some days that's easier than others. But the reframe — from 'how does it look' to 'what has it done' — has been the most useful thing anyone ever said to me.", category:"Body Image", readingTime:2, createdAt:"2026-02-09T16:00:00Z", reactions:{heart:612,hug:423,meToo:489,strength:289}, triggerWarnings:[] },

  /* Loss */
  { id:"s47", title:"What the Miscarriage Was", content:"We don't talk about miscarriage the way we should. People said it was very common, which is true and also not comfort. They said at least it was early, which tells you something about how we think about these things. It was early. It was also something we had already, privately, begun to love. I named her in my head. I never told anyone that part. I'm telling it here. Her name was going to be Elowen. I don't know why that feels important to put somewhere. It just does. She was real to us. That matters, whatever the calendar says about how long.", category:"Loss", readingTime:2, createdAt:"2026-03-07T21:00:00Z", reactions:{heart:789,hug:634,meToo:312,strength:423}, triggerWarnings:["Pregnancy loss"] },
  { id:"s48", title:"The Dog", content:"People will minimise this and I need to say it anyway: I am grieving my dog. Properly, deeply grieving. He was with me through my divorce, through my mother's illness, through the years I lived alone and had no one to come home to. He was the constant in every hard chapter. When people say 'it was just a dog' I don't argue anymore. I know what he was. He was the whole shape of my mornings for eleven years. The grief is real. It counts.", category:"Loss", readingTime:2, createdAt:"2026-02-27T18:00:00Z", reactions:{heart:934,hug:712,meToo:456,strength:267}, triggerWarnings:[] },
  { id:"s49", title:"The Longest Relationship I Had", content:"My cat was with me for seventeen years. He arrived when I was twenty-two and alone in a new city and he left last spring. He saw me through two relationships, a career change, a move, a period of serious illness, and things I haven't told anyone. He sat next to me through all of it with the complete indifference of a cat, which is somehow the best kind of company for bad things. I know how this sounds. I know how grief for a pet is received. I don't care anymore. He was real and his absence is real.", category:"Loss", readingTime:2, createdAt:"2026-03-03T20:00:00Z", reactions:{heart:823,hug:634,meToo:445,strength:201}, triggerWarnings:[] },

  /* Survival — self-harm recovery */
  { id:"s50", title:"The Scars", content:"I have scars. I don't hide them anymore, which took years. Someone asked me about them once on a beach and I said, simply: those are from a time when I didn't have better ways to manage what I was feeling. And then I said: I have better ways now. The conversation moved on. I spent so long believing the scars were evidence of something permanent in me. They're evidence of the opposite. They're evidence that I survived something I didn't yet have the tools to survive differently. I have the tools now. The scars are old. I'm not.", category:"Survival", readingTime:2, createdAt:"2026-03-16T11:00:00Z", reactions:{heart:934,hug:745,meToo:267,strength:812}, triggerWarnings:["Self-harm recovery — scars"] }
];

/* ============================================================
   ADVICE TIPS — 35 entries across 14 categories
   ============================================================ */
const DEFAULT_TIPS = [
  { id:"t1",  title:"Name it before it grows",         content:"When anxiety starts, I say it out loud — even if I'm alone. 'I'm having anxiety right now.' It sounds clinical but it separates you from the feeling. You're not the anxiety. You're the person noticing it. That tiny gap is everything.", category:"Anxiety", contributor:"Lived with GAD for 12 years" },
  { id:"t2",  title:"The 5-4-3-2-1 method",            content:"Five things you can see. Four you can touch. Three you can hear. Two you can smell. One you can taste. It sounds rote and it is. That's why it works — when your brain is in a loop, this interrupts the loop. I use it in supermarkets, on trains, at 3am.", category:"Anxiety", contributor:"Panic attacks since 17, now 31" },
  { id:"t3",  title:"Set a timer, then decide",         content:"I don't trust any thought I have during a spike. I've learned to set a fifteen-minute timer before I send any message, make any decision, or leave any room. After fifteen minutes the thought is usually still there but I can tell which parts were the anxiety and which parts were actually true.", category:"Anxiety", contributor:"Anxiety and OCD in recovery" },
  { id:"t4",  title:"Lower the bar completely",        content:"When I'm deep in depression, showering counts. Eating something counts. Getting to the sofa instead of staying in bed counts. The bar doesn't have to be productive or meaningful. It can just be breathing. Some days that's the entire goal.", category:"Depression", contributor:"Seven years of major depressive disorder" },
  { id:"t5",  title:"Tell one person",                 content:"I spent years telling no one. Saying it out loud to one safe person — not to be fixed, just heard — changed something. Not because they had answers. Because carrying it alone was making it heavier.", category:"Depression", contributor:"In recovery from depression and isolation" },
  { id:"t6",  title:"Track one small thing",           content:"At my worst, I started writing one thing per day that I did. Not accomplishments. Just things. Went outside. Ate lunch. Replied to the email. Looking back after two weeks and seeing a list of things I'd done when I thought I'd done nothing — that was the first evidence I had that I was still functioning. Evidence mattered when feelings lied.", category:"Depression", contributor:"Recurrent depression, ten years managed" },
  { id:"t7",  title:"Let the waves come",              content:"I spent the first year after my father died trying to manage my grief — scheduling when I could cry, keeping it in its box. Then I learned to just let it come when it comes. Fighting it used every bit of energy I needed for everything else.", category:"Grief", contributor:"Lost my father three years ago" },
  { id:"t8",  title:"Keep something ordinary",         content:"People said start fresh — change everything. I kept making coffee the exact way we always made it. Some ordinary things aren't reminders of the loss. They're threads back to the person who existed before it.", category:"Grief", contributor:"Widowed at 44" },
  { id:"t9",  title:"You don't have to be over it",   content:"There is no timeline. Anyone who gives you one is wrong. Grief is not a project with a deadline. It's love that changed shape. I stopped trying to get over it and started figuring out how to carry it. That was the thing that helped.", category:"Grief", contributor:"Bereaved parent" },
  { id:"t10", title:"One hour, not forever",           content:"I couldn't think about never again. It was too large a thing to hold. 'I won't drink today' was still too big on bad days. So I thought about the next hour. That's still how I do it sometimes. Just the next hour. Then the one after that.", category:"Addiction Recovery", contributor:"Four years sober from alcohol" },
  { id:"t11", title:"Shame is the engine",             content:"Shame told me I was too far gone to be worth helping. That was a lie addiction told me. Shame keeps you using. Addressing the shame is part of the recovery, not a distraction from it.", category:"Addiction Recovery", contributor:"Former opioid user, 2 years clean" },
  { id:"t12", title:"Find the boring parts first",     content:"Early recovery, everyone talks about the big emotional work. That's real. But the thing that nearly undid me was boredom. I didn't know what to do with evenings. Find something for the evenings first. Something boring and regular. For me it was going to the gym. I needed somewhere to be.", category:"Addiction Recovery", contributor:"Cocaine recovery, 18 months clean" },
  { id:"t13", title:"One meal at a time",              content:"I couldn't think about the whole day. I thought about one meal. Then the next one. Recovery doesn't happen all at once. It happens one decision at a time, and some of those decisions are just: eat this thing, now. That's enough. You don't have to feel good about it yet.", category:"Eating Disorders", contributor:"In recovery, working with a dietitian" },
  { id:"t14", title:"Tell your treatment team everything", content:"I told my therapist a curated version of what was happening for six months. The real progress started when I was honest about the parts I was hiding. The parts you hide are usually the parts that most need to be seen. That's why you're hiding them.", category:"Eating Disorders", contributor:"Anorexia recovery, three years" },
  { id:"t15", title:"Bad weeks aren't failure",        content:"I had bad weeks a year into recovery. I felt like I'd failed everything. My dietitian said: this is the work, not a sign the work isn't working. Bad weeks are data about where you still need support, not proof that you can't be supported. I needed to hear that more than once before I believed it.", category:"Eating Disorders", contributor:"Bulimia recovery, ongoing" },
  { id:"t16", title:"Shorter trips back",              content:"Progress in PTSD isn't about never going back. It's about shorter trips. The flashbacks aren't going to end overnight. But they got shorter. I return faster. I know where I am sooner. That is real progress, even when it doesn't feel like it.", category:"PTSD", contributor:"PTSD following assault, in therapy two years" },
  { id:"t17", title:"Tell your therapist the worst thing", content:"I held back the worst part for a year. My therapist eventually said: whatever you're not telling me is probably the thing we need. She was right. The thing I wasn't saying was the centre of it. It's scary. Do it anyway.", category:"PTSD", contributor:"Childhood trauma, adult recovery" },
  { id:"t18", title:"Parallel company",                content:"When I couldn't face actual social contact, I started going to cafes to work. No conversation required. Just being in a space where other people were living their ordinary days around me. It helped more than I expected. Humans need proximity. You don't always need interaction.", category:"Loneliness", contributor:"Chronically lonely, slowly less so" },
  { id:"t19", title:"Be a regular somewhere",          content:"Go to the same coffee shop on the same morning every week. Get the same thing. After six weeks, someone will recognise you. After three months, someone will say good morning without being asked. This is not friendship. But it's the level below friendship, and you have to build from the ground up.", category:"Loneliness", contributor:"Rebuilt social life after isolation" },
  { id:"t20", title:"Stop trying to sleep",            content:"The thing that helped my insomnia most was stopping trying to sleep. I started getting up if I hadn't fallen asleep in twenty minutes and doing something quiet — reading a physical book — until I felt sleepy. Lying there willing myself to sleep was making it worse. The effort was the problem.", category:"Insomnia", contributor:"Chronic insomnia managed, five years" },
  { id:"t21", title:"The same wake time every day",    content:"My sleep specialist said: keep the same wake time, even on weekends, even after a bad night. It sounds punishing. It rebuilt my sleep cycle in about three weeks. Sleeping in after bad nights wrecks the anchor. One consistent time is worth more than any supplement.", category:"Insomnia", contributor:"Sleep disorder, long-term management" },
  { id:"t22", title:"Stop performing recovery",        content:"I burned out and immediately put pressure on myself to recover correctly — journaling, meditating, side projects, podcasts. That's just burnout with better branding. Burnout recovery looks like doing less. Actually less. It's uncomfortable because doing nothing feels like failing. It isn't.", category:"Burnout", contributor:"Left corporate, rebuilding slowly" },
  { id:"t23", title:"Rest before you're empty",        content:"The mistake I made for years was treating rest as a reward for finishing everything. Nothing is ever finished. I kept moving the finish line. Rest is not a prize you earn. It is maintenance. You don't wait for the car to break down before putting in oil.", category:"Burnout", contributor:"Chronic burnout, learning differently now" },
  { id:"t24", title:"Notice what you resent",          content:"My therapist asked me: what are you doing that you resent? I had a long list. That list was the map of what to change. Resentment is useful data. It tells you where you've agreed to things that aren't sustainable. Pay attention to it before it turns into collapse.", category:"Burnout", contributor:"Two burnout episodes, prevention mode now" },
  { id:"t25", title:"Have one goal, not many",         content:"At social events, my only goal is to have one real conversation. One. Not to network, not to be impressive, not to seem okay. One real exchange with one person. When that's happened, I've succeeded. Everything else is a bonus. Lowering the target made it achievable.", category:"Social Anxiety", contributor:"Social anxiety managed with CBT" },
  { id:"t26", title:"You are not the most observed person in the room", content:"Social anxiety lies about how much attention you're receiving. People are mostly thinking about themselves. I spent years assuming I was being closely monitored and judged. I wasn't. Most people are running their own version of this anxiety, pointed at themselves. You are less visible than you think.", category:"Social Anxiety", contributor:"Social anxiety since adolescence" },
  { id:"t27", title:"It will end in ten minutes",      content:"When a panic attack starts, I tell myself: this will be over in ten minutes. It always is. Not comfortable — but over. Knowing it has a ceiling matters. The fear of the fear extends it. If I can accept that it's happening and it will pass, it passes faster.", category:"Panic Attacks", contributor:"Panic disorder, three years managed" },
  { id:"t28", title:"Don't avoid the next thing",      content:"Avoiding what triggered the panic attack teaches your brain that the avoidance kept you safe. It didn't. Go back. Not immediately, not alone if possible, but go back. Every avoidance makes the fear slightly larger. Every return makes it slightly smaller.", category:"Panic Attacks", contributor:"Exposure therapy changed my life" },
  { id:"t29", title:"Learn your patterns first",       content:"I went straight from my difficult relationship into the next one and replicated the same dynamic almost exactly. I didn't understand my own patterns yet. Do the work between relationships, not inside the next one. It is less lonely to be alone and working than to be together and repeating.", category:"Relationship Trauma", contributor:"Two years single, finally understanding myself" },
  { id:"t30", title:"Chemistry might be familiarity",  content:"I used to feel incredible chemistry with emotionally unavailable people. I now understand that wasn't chemistry — it was recognition. It felt like home because it matched what I grew up in. I'm learning to be curious about people who are consistently kind. They feel unfamiliar. That's not a bad sign.", category:"Relationship Trauma", contributor:"Therapy for attachment patterns, 18 months" },
  { id:"t31", title:"It wasn't your job",              content:"As a child, I thought my job was to keep the adults around me stable. I got very good at it. I'm still getting good at not doing it. You were not responsible for what happened in that house. You were a child. The management and repair was never supposed to be your job.", category:"Childhood Trauma", contributor:"CPTSD diagnosis, in long-term therapy" },
  { id:"t32", title:"The adaptations made sense then", content:"Everything I do that causes me problems now made perfect sense in the environment I learned it in. Hypervigilance, emotional shutting-down, the need to make myself small — these were survival tools. I'm not broken. I'm running software designed for a previous environment. It can be updated. Slowly, with help, it can be updated.", category:"Childhood Trauma", contributor:"Childhood emotional neglect, adult recovery" },
  { id:"t33", title:"Have an alternative ready before you need it", content:"In moments of crisis you cannot design a new strategy. The strategy has to already be decided. For me it's: call one specific person, then go to one specific room, then do one specific thing. I decided this in a calm moment and I follow the plan.", category:"Self-Harm Recovery", contributor:"Five years without self-harm" },
  { id:"t34", title:"Tell a professional about the urges", content:"I told my therapist when I had harmed. It took longer to tell her when I was having strong urges. The urges are where the intervention is possible. The incidents are after. Get the urges into the room. That's where the work can happen.", category:"Self-Harm Recovery", contributor:"Recovery ongoing, working with a therapist" },
  { id:"t35", title:"Recovery is a practice, not a place", content:"I had an urge last week. I have been in recovery for four years. Having the urge doesn't mean I've failed. It means I'm still human and stress is real. I used my tools. I got through it. Recovery is not a place you arrive at and stay. It's a practice you maintain. That's not a failure. That's just what it is.", category:"Self-Harm Recovery", contributor:"Long-term recovery, still doing the work" }
];

/* ============================================================
   TERMINOLOGY — 52 entries A–Z
   ============================================================ */
const DEFAULT_TERMS = [
  { term:"Agoraphobia", definition:"An anxiety disorder characterised by fear of situations where escape might be difficult or help unavailable during a panic attack. Often misunderstood as fear of open spaces — it is more accurately fear of situations where one feels trapped or unsafe.", heaviness:"orange", correctUsage:"My agoraphobia makes public transport very difficult — I need to be able to leave at any time.", incorrectUsage:"She's agoraphobic — she just doesn't like going out. (agoraphobia is a clinical diagnosis, not social introversion)" },
  { term:"Anhedonia", definition:"The reduced or absent ability to feel pleasure in activities that were previously enjoyable. A key symptom of depression that is often overlooked because it doesn't present as visible sadness.", heaviness:"orange", correctUsage:"Anhedonia means I haven't been able to enjoy music or time with friends the way I used to.", incorrectUsage:"You're just bored — everyone goes through phases. (anhedonia is a clinical symptom, not temporary disinterest)" },
  { term:"Anxiety", definition:"A mental health condition characterised by persistent, excessive worry or fear that is difficult to control. Can manifest physically (racing heart, shortness of breath) as well as emotionally and cognitively.", heaviness:"yellow", correctUsage:"I live with anxiety, which makes crowded places difficult for me.", incorrectUsage:"I'm so anxious about this exam! (when describing ordinary, temporary pre-event nervousness)" },
  { term:"Attachment Trauma", definition:"Psychological harm resulting from disrupted, unreliable, or abusive early caregiving relationships. Affects how a person forms and maintains relationships throughout their life.", heaviness:"orange", correctUsage:"My therapist helped me understand that my difficulties in relationships stem from attachment trauma in childhood.", incorrectUsage:"Everyone has attachment trauma — it's just called having parents. (minimising a serious developmental impact)" },
  { term:"Avoidance", definition:"A coping pattern in which a person steers away from distressing thoughts, feelings, situations, or people. Provides short-term relief but maintains and strengthens anxiety and PTSD over time.", heaviness:"yellow", correctUsage:"My avoidance of crowded places has grown because I never challenge the fear.", incorrectUsage:"Just avoid everything that upsets you. (avoidance, when chronic, is a symptom to address rather than a sustainable strategy)" },
  { term:"Burnout", definition:"A state of chronic stress leading to physical and emotional exhaustion, cynicism, detachment, and feelings of ineffectiveness. Recognised as an occupational phenomenon by the World Health Organisation.", heaviness:"yellow", correctUsage:"After two years of overworking, I experienced burnout and had to take medical leave.", incorrectUsage:"I'm totally burned out from that party. (burnout is a sustained condition, not single-event tiredness)" },
  { term:"Catastrophising", definition:"A cognitive distortion in which a person overestimates the likelihood or magnitude of negative outcomes, or assumes the worst-case scenario is inevitable. A common feature of anxiety and depression.", heaviness:"yellow", correctUsage:"My therapist helped me recognise I was catastrophising when I assumed one mistake would end my career.", incorrectUsage:"You're catastrophising — you're fine. (dismissing someone's fears without engaging with what's underneath them)" },
  { term:"Codependency", definition:"A relational pattern in which someone excessively prioritises another's needs and emotions at the expense of their own. Often develops in relationships involving addiction, chronic illness, or emotional unavailability.", heaviness:"yellow", correctUsage:"I realised my relationship had become codependent when I couldn't make any decision without their approval.", incorrectUsage:"They're codependent because they care too much. (codependency is a relational dynamic, not simply strong affection)" },
  { term:"Complex PTSD (C-PTSD)", definition:"A form of PTSD resulting from prolonged, repeated trauma — particularly in childhood or situations from which escape was difficult. Includes features beyond standard PTSD: difficulty regulating emotions, distorted self-perception, and relational difficulties.", heaviness:"red", correctUsage:"I have C-PTSD from years of childhood neglect, which affects how I relate to people and regulate my emotions.", incorrectUsage:"It's just PTSD — same thing. (C-PTSD is a distinct presentation with different treatment needs)" },
  { term:"Compulsion", definition:"A repetitive behaviour or mental act that a person feels driven to perform to reduce anxiety or prevent a feared outcome. A core feature of OCD. Compulsions provide short-term relief but strengthen the underlying cycle.", heaviness:"orange", correctUsage:"Checking the locks repeatedly is a compulsion — it temporarily reduces anxiety but makes my OCD worse over time.", incorrectUsage:"I'm so OCD about tidying up. (compulsions cause significant distress and impairment; they are not preferences)" },
  { term:"Coping Mechanism", definition:"A strategy — conscious or unconscious — used to manage stress, painful emotions, or difficult experiences. Can be adaptive (helpful long-term) or maladaptive (harmful or temporarily effective but ultimately counterproductive).", heaviness:"green", correctUsage:"Running became a healthy coping mechanism for managing my anxiety.", incorrectUsage:"Their coping mechanism is just an excuse. (coping mechanisms are real psychological strategies, not rationalisations)" },
  { term:"Crisis", definition:"A period of intense psychological distress in which a person's usual coping strategies are insufficient and they may be at risk of harm. A mental health crisis requires timely, compassionate support.", heaviness:"red", correctUsage:"I was in crisis last year and called a hotline — it helped me get through the night.", incorrectUsage:"Everything is a crisis with her. (repeated dismissal prevents people from seeking help when genuinely at risk)" },
  { term:"Depersonalisation", definition:"A dissociative experience in which a person feels detached from their own thoughts, feelings, body, or identity — as if watching themselves from outside. Can occur in isolation or as part of a dissociative disorder.", heaviness:"orange", correctUsage:"During the panic attack, I felt as though I was watching myself from across the room.", incorrectUsage:"I just feel weird today — total depersonalisation. (depersonalisation is a specific and distressing clinical experience, not general oddness)" },
  { term:"Depression", definition:"A serious mental health condition characterised by persistent low mood, loss of interest or pleasure, changes in sleep and appetite, low energy, difficulty concentrating, and in severe cases, thoughts of self-harm or suicide. Not a choice or a character flaw.", heaviness:"orange", correctUsage:"I was diagnosed with depression and am currently in treatment with therapy and medication.", incorrectUsage:"I'm so depressed about the weather. (depression is a clinical condition, not a synonym for temporary sadness)" },
  { term:"Derealisation", definition:"A dissociative experience in which the external world feels unreal, dreamlike, or distorted. Often occurs alongside depersonalisation. Both can be trauma responses or symptoms of anxiety and panic disorder.", heaviness:"orange", correctUsage:"When I'm very anxious, I sometimes experience derealisation — the room feels like a film set rather than somewhere real.", incorrectUsage:"This feels surreal — total derealisation! (derealisation is a clinical experience with specific features, not general surprise)" },
  { term:"Dissociation", definition:"A disconnection from one's thoughts, feelings, body, surroundings, or sense of identity. Ranges from mild (daydreaming) to severe (dissociative identity disorder). Often occurs as a protective response to overwhelming stress or trauma.", heaviness:"orange", correctUsage:"During stressful situations, I sometimes dissociate and can't remember what was said for several minutes.", incorrectUsage:"I dissociate from problems I don't want to deal with. (dissociation is not a voluntary choice to avoid things)" },
  { term:"Emotional Dysregulation", definition:"Difficulty managing the intensity, duration, or expression of emotional responses. Can manifest as emotional outbursts, prolonged distress, or emotional numbness. Associated with BPD, ADHD, C-PTSD, and other conditions.", heaviness:"orange", correctUsage:"My emotional dysregulation means I can go from calm to overwhelmed very quickly — I'm working on it with DBT.", incorrectUsage:"They're just dramatic. (emotional dysregulation is a neurological and psychological pattern, not performance)" },
  { term:"Emotional Numbing", definition:"A state of reduced emotional responsiveness, often as a protective mechanism following trauma, or a feature of depression or PTSD. The person may feel disconnected from their own feelings.", heaviness:"orange", correctUsage:"After the accident, I experienced emotional numbing and couldn't cry even when I wanted to.", incorrectUsage:"They're emotionally numb because they don't care. (numbing is protection, not indifference)" },
  { term:"Exposure Therapy", definition:"An evidence-based treatment in which a person gradually confronts feared situations, memories, or objects in a safe environment, reducing avoidance and fear over time. Used for phobias, OCD, PTSD, and anxiety disorders.", heaviness:"green", correctUsage:"Exposure therapy helped me return to driving after my accident by gradually reintroducing me to being in a car.", incorrectUsage:"Just throw them in the deep end — that's exposure therapy. (true exposure therapy is gradual and conducted with professional support)" },
  { term:"Flashback", definition:"A vivid, intrusive re-experiencing of a past traumatic event, in which the person may feel as though the event is happening now. A hallmark symptom of PTSD, often triggered by sensory cues associated with the original trauma.", heaviness:"orange", correctUsage:"Loud arguments trigger flashbacks to my childhood home — I become unable to process what is happening in the present.", incorrectUsage:"That movie gave me flashbacks to my childhood. (when used to describe nostalgic memory rather than trauma re-experiencing)" },
  { term:"Gaslighting", definition:"A form of psychological manipulation in which a person causes another to question their own memory, perception, or sanity. A serious form of emotional abuse typically occurring in ongoing relationships.", heaviness:"orange", correctUsage:"My partner told me things hadn't happened that clearly had. I later understood this was gaslighting.", incorrectUsage:"Stop gaslighting me — I just disagree with you. (gaslighting is a deliberate, sustained pattern of manipulation, not disagreement)" },
  { term:"Grounding", definition:"Techniques used to return a person to the present moment during dissociation, flashbacks, or panic. Includes the 5-4-3-2-1 sensory method, controlled breathing, and physical contact with objects.", heaviness:"green", correctUsage:"When I feel a flashback beginning, I use grounding techniques to reconnect with where I am.", incorrectUsage:"Just ground yourself — it's easy. (grounding takes practice and is not a simple fix, particularly in acute trauma responses)" },
  { term:"Hypervigilance", definition:"A state of heightened alertness and sensitivity to perceived threats, common in trauma survivors. The nervous system remains on alert as if danger is always imminent. Exhausting to live with and often invisible to others.", heaviness:"orange", correctUsage:"After living in an unsafe home, I developed hypervigilance — I scan every room I enter and can't relax.", incorrectUsage:"She's hypervigilant because she's paranoid. (hypervigilance is a nervous system adaptation to threat, not a personality flaw)" },
  { term:"Imposter Syndrome", definition:"A psychological pattern in which a person doubts their own accomplishments and fears being exposed as a fraud, despite evidence of competence. Common among high achievers and in environments where one belongs to a minority group.", heaviness:"yellow", correctUsage:"Even after several promotions, I struggled with imposter syndrome and feared being exposed as undeserving.", incorrectUsage:"Everyone has imposter syndrome — it's just insecurity. (while common, imposter syndrome is a meaningful experience that can be debilitating)" },
  { term:"Intrusive Thoughts", definition:"Unwanted, involuntary thoughts, images, or urges that feel distressing and out of character. A feature of OCD, anxiety, and PTSD. They do not represent a person's true desires — the distress they cause typically proves this.", heaviness:"orange", correctUsage:"My intrusive thoughts about harm horrify me — my therapist helped me understand they're symptoms, not desires.", incorrectUsage:"If you have thoughts like that you must be dangerous. (intrusive thoughts are symptoms causing distress because they contradict the person's values)" },
  { term:"Learned Helplessness", definition:"A state in which a person stops trying to improve their situation because past experience has taught them that their actions have no effect on outcomes. Helps explain how prolonged trauma can affect agency and motivation.", heaviness:"yellow", correctUsage:"After years of nothing I did mattering at home, I developed learned helplessness that has been hard to undo.", incorrectUsage:"They've just given up — that's an excuse. (learned helplessness is a genuine psychological response to chronic uncontrollability)" },
  { term:"Mania", definition:"A distinct period of abnormally elevated or irritable mood, increased energy, decreased need for sleep, and often impaired judgement. A feature of bipolar disorder. Mania is a medical condition, not positive energy.", heaviness:"red", correctUsage:"During my manic episodes, I make decisions I later regret and feel invincible in ways that get me into difficulty.", incorrectUsage:"She's so manic today — so much energy! (mania is a serious mental health episode, not enthusiasm)" },
  { term:"Mental Health", definition:"A state of psychological, emotional, and social wellbeing. Not simply the absence of mental illness — it includes the ability to cope with stress, function in daily life, and maintain relationships. Everyone has mental health, and it fluctuates.", heaviness:"green", correctUsage:"I prioritise my mental health by attending therapy and being intentional about rest.", incorrectUsage:"Mental health is just an excuse. (mental health is a real dimension of overall health, not a rationalisation)" },
  { term:"Mood Disorder", definition:"A category of mental health conditions primarily characterised by disturbances in a person's mood state. Includes depressive disorders, bipolar disorder, and cyclothymia.", heaviness:"orange", correctUsage:"I have a mood disorder that requires medication management and regular check-ins with my psychiatrist.", incorrectUsage:"Everyone has mood disorders — we all have bad days. (mood disorders are clinical diagnoses distinct from ordinary mood variation)" },
  { term:"Obsessive-Compulsive Disorder (OCD)", definition:"A mental health condition characterised by obsessions (unwanted intrusive thoughts that cause distress) and compulsions (repetitive behaviours performed to reduce that distress). OCD is not about tidiness — it takes many forms.", heaviness:"orange", correctUsage:"My OCD involves intrusive thoughts and mental rituals that take up hours of my day.", incorrectUsage:"I'm so OCD about having a neat desk. (OCD is a debilitating condition, not a preference for order)" },
  { term:"Panic Attack", definition:"A sudden episode of intense fear or physical discomfort, peaking within minutes, and involving symptoms such as racing heart, shortness of breath, chest pain, dizziness, sweating, and a sense of impending doom. Frightening but not physically dangerous.", heaviness:"orange", correctUsage:"I had a panic attack at the supermarket — I couldn't breathe and had to leave.", incorrectUsage:"I had a panic attack when my flight was delayed. (panic attacks are clinical episodes; stress about a delay is not the same)" },
  { term:"Post-Traumatic Stress Disorder (PTSD)", definition:"A mental health condition developing after experiencing or witnessing a traumatic event. Symptoms include flashbacks, nightmares, avoidance, emotional numbing, and hypervigilance, lasting more than a month and causing significant impairment.", heaviness:"red", correctUsage:"I was diagnosed with PTSD following the assault and am working through EMDR therapy.", incorrectUsage:"That test gave me PTSD. (PTSD is a clinical diagnosis, not a descriptor for a stressful experience)" },
  { term:"Psychosis", definition:"A mental state in which a person loses contact with reality, experiencing delusions or hallucinations. Can occur in schizophrenia, bipolar disorder, severe depression, and other conditions. Requires urgent professional care.", heaviness:"red", correctUsage:"During my psychotic episode, I heard voices and believed things that weren't true — it was terrifying.", incorrectUsage:"She's being psychotic — she's just overreacting. (psychosis is a medical emergency, not a synonym for irrational behaviour)" },
  { term:"Recovery", definition:"A personal, ongoing process of rebuilding wellbeing after illness, trauma, or addiction. Not linear — it includes setbacks — and looks different for every person. Not always a return to a previous state, but often the building of a new one.", heaviness:"green", correctUsage:"I am in recovery and have been sober for fourteen months, though it remains work.", incorrectUsage:"You're recovered now so you're fine. (recovery is lifelong for many conditions, not a fixed endpoint)" },
  { term:"Resilience", definition:"The capacity to adapt, function, and recover in the face of adversity. Not the absence of distress — it is the process of navigating it. Resilience is built, not innate, and varies across circumstances.", heaviness:"green", correctUsage:"My resilience has grown through difficult years, though it didn't protect me from being affected.", incorrectUsage:"Just be more resilient. (resilience is built with support, not a demand to feel less)" },
  { term:"Rumination", definition:"Repetitive, passive focus on negative feelings or upsetting experiences without moving toward resolution. A common feature of depression and anxiety. Maintains and deepens distress rather than helping process it.", heaviness:"yellow", correctUsage:"I spent weeks ruminating on the argument, replaying it constantly and feeling worse each time.", incorrectUsage:"Just stop ruminating — think about something else. (rumination is an automatic cognitive pattern, not a voluntary choice)" },
  { term:"Safe Person", definition:"An individual with whom someone feels genuinely secure and able to be honest without fear of judgement, rejection, or harm. Having at least one safe person is associated with significantly better mental health outcomes.", heaviness:"green", correctUsage:"My sister is my safe person — she knows everything and doesn't need me to perform.", incorrectUsage:"Safe person is just another word for best friend. (a safe person is specifically someone with whom psychological safety exists, which closeness doesn't guarantee)" },
  { term:"Schema", definition:"A deeply held belief or pattern about oneself, others, or the world — typically formed in early life. Harmful schemas (such as 'I am fundamentally unlovable') are a focus of Schema Therapy.", heaviness:"yellow", correctUsage:"My therapist identified a core schema of being defective, which affects how I interpret my relationships.", incorrectUsage:"That's just how they are — their schema. (schemas are meaningful, often painful patterns formed in adverse conditions, not fixed personality)" },
  { term:"Self-Compassion", definition:"Treating oneself with the same kindness, understanding, and patience one would offer a good friend during difficulty or failure. Research identifies self-compassion as a key factor in emotional resilience and recovery.", heaviness:"green", correctUsage:"I'm learning self-compassion — to speak to myself about my setbacks the way I'd speak to someone I cared about.", incorrectUsage:"Self-compassion is just self-pity. (self-compassion is an evidence-based practice associated with better outcomes, not passivity)" },
  { term:"Self-Harm", definition:"Deliberate injury to one's own body, typically as a way of coping with overwhelming emotional pain rather than with the intent to end one's life. Requires compassionate, non-judgmental support and clinical assessment.", heaviness:"red", correctUsage:"I have a history of self-harm that I'm working through in therapy — it was a coping mechanism I needed to replace.", incorrectUsage:"Self-harm is just attention-seeking. (self-harm is a sign of severe distress and requires care, not dismissal)" },
  { term:"Shame", definition:"The painful belief that one is fundamentally flawed, worthless, or unworthy of belonging. Distinguished from guilt (about behaviour) by its focus on the self as bad rather than the action. Drives concealment and disconnection.", heaviness:"orange", correctUsage:"Shame told me I was too broken to be worth helping — addressing that was central to my recovery.", incorrectUsage:"A bit of shame is good for people. (shame, unlike guilt, is associated with harmful psychological outcomes)" },
  { term:"Social Anxiety", definition:"An anxiety disorder characterised by intense fear of social situations in which one might be judged, embarrassed, or rejected. More than ordinary shyness — it causes significant avoidance and impairment in daily functioning.", heaviness:"yellow", correctUsage:"Social anxiety means I often leave events early or don't attend — it's not rudeness, it's fear.", incorrectUsage:"They're just shy — they'll grow out of it. (social anxiety is a diagnosable condition that benefits from specific treatment)" },
  { term:"Somatic Symptoms", definition:"Physical symptoms caused or worsened by psychological factors — pain, fatigue, nausea — with no medical cause, or symptoms disproportionate to a medical condition. The symptoms are real and not invented.", heaviness:"yellow", correctUsage:"My stress manifests as somatic symptoms — stomach pain and headaches that appear before difficult situations.", incorrectUsage:"It's all in their head. (somatic symptoms are genuinely experienced; the distinction is about origin, not reality)" },
  { term:"Stigma", definition:"Negative attitudes, prejudice, and discrimination directed at people with mental health conditions. Causes people to conceal symptoms, delay treatment, and face discrimination. It causes measurable, preventable harm.", heaviness:"yellow", correctUsage:"The stigma around depression stopped me from telling anyone for three years and delayed my recovery.", incorrectUsage:"People are too sensitive about stigma. (stigma is associated with delayed treatment and worse outcomes)" },
  { term:"Suicidal Ideation", definition:"Thoughts about ending one's own life. Ranges from passive (wishing to be dead) to active (planning a method). Always a serious symptom requiring compassionate, immediate support. Not manipulation or attention-seeking.", heaviness:"red", correctUsage:"During my lowest point, I experienced suicidal ideation and reached out to a crisis line, which helped me through the night.", incorrectUsage:"They're just saying it for attention. (suicidal ideation is always taken seriously — no exceptions)" },
  { term:"Survivor's Guilt", definition:"A form of guilt experienced by those who have survived an event in which others have not — or who have recovered when others have not. Common after accidents, disasters, and suicide loss.", heaviness:"orange", correctUsage:"I struggle with survivor's guilt after my brother's suicide — I can't reconcile why I got through my depression when he didn't.", incorrectUsage:"That doesn't make sense — you couldn't have saved them. (survivor's guilt is an emotional reality, not a logical position that can be argued away)" },
  { term:"Therapy", definition:"A professional process in which a trained therapist works with an individual to address emotional difficulties, mental health conditions, or relational patterns. Many evidence-based forms exist, including CBT, DBT, EMDR, and psychodynamic therapy.", heaviness:"green", correctUsage:"I've been in therapy for two years and it's the most useful thing I've ever done for my mental health.", incorrectUsage:"Therapy is for people who can't cope on their own. (therapy is a professional service, not evidence of weakness)" },
  { term:"Trauma", definition:"The lasting emotional, psychological, and physiological impact of an experience that overwhelms a person's ability to cope. Defined by its impact on the person, not the perceived severity of the event by others.", heaviness:"red", correctUsage:"Witnessing that accident caused me lasting trauma that I am still processing years later.", incorrectUsage:"That's not real trauma — worse things happen to people. (trauma is defined by the survivor's experience, not a comparison)" },
  { term:"Trigger", definition:"A stimulus — sensory, situational, or interpersonal — that activates a strong emotional or physiological response linked to a past difficult experience. Real and involuntary, not a sign of weakness or oversensitivity.", heaviness:"yellow", correctUsage:"Loud arguments are a trigger for me because of my childhood — I need to step out when they occur.", incorrectUsage:"Everything triggers you — you're too sensitive. (dismissing triggers invalidates real responses to real experiences)" },
  { term:"Validation", definition:"The acknowledgement that another person's thoughts, feelings, and experiences are understandable and make sense given their circumstances. Does not require agreement — requires recognition.", heaviness:"green", correctUsage:"My therapist validated my feelings about the situation, which helped me trust my own perceptions.", incorrectUsage:"Validating everything just enables bad behaviour. (validating feelings is distinct from endorsing all actions that arise from them)" },
  { term:"Vulnerability", definition:"The willingness to be honestly seen — to share, to risk, to engage without certainty of outcome. Research identifies vulnerability as foundational to connection, creativity, and healing.", heaviness:"green", correctUsage:"Sharing my story required real vulnerability, but it helped me connect with people who understood.", incorrectUsage:"Vulnerability is weakness. (vulnerability is the starting point of genuine human connection and a component of courage)" },
  { term:"Window of Tolerance", definition:"The optimal zone of arousal in which a person can function effectively, process emotions, and respond rather than react. Trauma and chronic stress narrow this window. A central concept in trauma-informed therapy.", heaviness:"yellow", correctUsage:"When I'm outside my window of tolerance, I either shut down completely or react in ways I later regret.", incorrectUsage:"That's just them being oversensitive. (responses outside the window of tolerance are neurological, not character flaws)" },
  { term:"Withdrawal", definition:"The physical and psychological symptoms that occur when a person stops or reduces use of a substance they are dependent on. Ranges from uncomfortable to medically dangerous. Should be managed with professional support.", heaviness:"red", correctUsage:"Alcohol withdrawal can be medically serious — I was supervised throughout mine by a doctor.", incorrectUsage:"Just stop taking it — withdrawal is just discomfort. (withdrawal from alcohol and certain medications can be life-threatening)" }
];

/* ============================================================
   Crisis resources (18 countries + international)
   ============================================================ */
const CRISIS_RESOURCES = [
  { country:"United States",   lines:[{ name:"988 Suicide & Crisis Lifeline", contact:"Call or text 988", note:"24/7, free" }, { name:"Crisis Text Line", contact:"Text HOME to 741741", note:"Text-based, 24/7" }] },
  { country:"United Kingdom",  lines:[{ name:"Samaritans", contact:"116 123", note:"Free, 24/7" }, { name:"PAPYRUS (under 35)", contact:"0800 068 4141", note:"Mon–Fri 9am–10pm" }] },
  { country:"Canada",          lines:[{ name:"Talk Suicide Canada", contact:"1-833-456-4566", note:"24/7" }, { name:"Crisis Text Line Canada", contact:"Text HOME to 45645", note:"24/7" }] },
  { country:"Australia",       lines:[{ name:"Lifeline Australia", contact:"13 11 14", note:"24/7" }, { name:"Beyond Blue", contact:"1300 22 4636", note:"24/7" }] },
  { country:"New Zealand",     lines:[{ name:"Lifeline New Zealand", contact:"0800 543 354", note:"24/7" }, { name:"Need to Talk?", contact:"Text or call 1737", note:"24/7" }] },
  { country:"Ireland",         lines:[{ name:"Samaritans Ireland", contact:"116 123", note:"Free, 24/7" }, { name:"Pieta House", contact:"116 123", note:"24/7" }] },
  { country:"India",           lines:[{ name:"iCall", contact:"9152987821", note:"Mon–Sat 8am–10pm" }, { name:"Vandrevala Foundation", contact:"1860-2662-345", note:"24/7" }] },
  { country:"Philippines",     lines:[{ name:"Hopeline Philippines", contact:"02-8804-4673", note:"24/7" }, { name:"In Touch Community Services", contact:"02-8893-7603", note:"Mon–Fri 9am–5pm" }] },
  { country:"South Africa",    lines:[{ name:"SADAG", contact:"0800 456 789", note:"Free, 24/7" }, { name:"Lifeline South Africa", contact:"0861 322 322", note:"24/7" }] },
  { country:"Brazil",          lines:[{ name:"CVV (Centro de Valorização da Vida)", contact:"188", note:"24/7" }] },
  { country:"Germany",         lines:[{ name:"TelefonSeelsorge", contact:"0800 111 0 111", note:"Free, 24/7" }, { name:"TelefonSeelsorge", contact:"0800 111 0 222", note:"Free, 24/7 (alt)" }] },
  { country:"France",          lines:[{ name:"Numéro National de Prévention du Suicide", contact:"3114", note:"24/7" }, { name:"Suicide Écoute", contact:"01 45 39 40 00", note:"24/7" }] },
  { country:"Japan",           lines:[{ name:"TELL Lifeline (English)", contact:"03-5774-0992", note:"Daily 9am–11pm" }, { name:"Inochi no Denwa", contact:"0570-783-556", note:"24/7" }] },
  { country:"South Korea",     lines:[{ name:"Korean Suicide Prevention Hotline", contact:"1393", note:"24/7" }, { name:"Lifeline Korea", contact:"1588-9191", note:"24/7" }] },
  { country:"Mexico",          lines:[{ name:"SAPTEL", contact:"55 5259-8121", note:"24/7" }] },
  { country:"Netherlands",     lines:[{ name:"113 Zelfmoordpreventie", contact:"0800 0113", note:"Free, 24/7" }] },
  { country:"Sweden",          lines:[{ name:"Mind Självmordslinjen", contact:"90101", note:"24/7" }] },
  { country:"Norway",          lines:[{ name:"Mental Helse", contact:"116 123", note:"24/7" }] }
];

const CRISIS_INTERNATIONAL = [
  { name:"International Association for Suicide Prevention (IASP)", url:"https://www.iasp.info/resources/Crisis_Centres/" },
  { name:"Befrienders Worldwide", url:"https://www.befrienders.org" },
  { name:"International Suicide Prevention Wiki", url:"https://suicideprevention.wikia.org" }
];

/* ============================================================
   State — load from localStorage or fall back to defaults.
   Separate try/catch guards against corrupted JSON.
   ============================================================ */
const State = {
  stories: (() => { try { const v = localStorage.getItem('ua_stories'); return v ? JSON.parse(v) : [...DEFAULT_STORIES]; } catch { return [...DEFAULT_STORIES]; } })(),
  tips:    (() => { try { const v = localStorage.getItem('ua_tips');    return v ? JSON.parse(v) : [...DEFAULT_TIPS];    } catch { return [...DEFAULT_TIPS];    } })(),
  terms:   (() => { try { const v = localStorage.getItem('ua_terms');   return v ? JSON.parse(v) : [...DEFAULT_TERMS];  } catch { return [...DEFAULT_TERMS];  } })(),
  save: {
    stories: () => { try { localStorage.setItem('ua_stories', JSON.stringify(State.stories)); } catch(e) { console.warn('Storage full', e); } },
    tips:    () => { try { localStorage.setItem('ua_tips',    JSON.stringify(State.tips));    } catch(e) { console.warn('Storage full', e); } },
    terms:   () => { try { localStorage.setItem('ua_terms',   JSON.stringify(State.terms));   } catch(e) { console.warn('Storage full', e); } }
  }
};

/* ============================================================
   Pure utilities
   ============================================================ */
function escHtml(str) {
  if (str == null) return '';
  return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
}
function randomItem(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function randomStory()   { return randomItem(State.stories); }
function formatDate(iso) { try { return new Date(iso).toLocaleDateString(undefined, { month:'long', day:'numeric', year:'numeric' }); } catch { return ''; } }
function wordCount(str)  { return str ? str.trim().split(/\s+/).length : 0; }
function readingTime(str){ return Math.max(1, Math.ceil(wordCount(str) / 200)); }
